#
# Configuration for the BankID IdP.
#
server:
  port: 8443
  servlet:
    session:
      cookie:
        name: BANKIDSESSION
      timeout: 15m
    context-path: /bankid/idp
  ssl:
    enabled: true
    key-store: classpath:ssl.jks
    key-store-type: JKS
    key-alias: local
    key-store-password: secret
    key-password: secret
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    path: "/icandothis"

management:
  server:
    port: 8444
  endpoint:
    health:
      status:
        order:
        - DOWN
        - OUT_OF_SERVICE
        - UP
        - WARNING
        - UNKNOWN
        http-mapping:
          WARNING: 503
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, loggers

spring:
  messages:
    basename: messages,idp-errors/idp-error-messages
    
bankid:
  server-root-certificate: classpath:bankid-trust-prod.crt
  service-url: https://appapi2.bankid.com/rp/v6.0
  qr-code:
    size: 300
    image-format: PNG
  user-message-defaults:
    fallback-sign-text:
      text: "Jag skriver härmed under den information som visades på föregående sida." 
      format: plain-text
    login-text:
      text: "*Tänk på!* Logga aldrig in med ditt BankID då någon ringer och ber dig logga in."
      format: simple-markdown-v1
  authn:
    resume-path: /resume 
    provider-name: "BankID"
    supported-loas:
    - http://id.swedenconnect.se/loa/1.0/uncertified-loa3
    entity-categories:
    - http://id.elegnamnden.se/ec/1.0/loa3-pnr
    - http://id.swedenconnect.se/ec/1.0/loa3-name
    - http://id.elegnamnden.se/sprop/1.0/mobile-auth
    - http://id.elegnamnden.se/sprop/1.0/scal2
    - http://id.swedenconnect.se/general-ec/1.0/secure-authenticator-binding    
    authn-path: "/bankid"
    
#
# The SAML IdP configuration
#    
saml:
  idp:
    entity-id: https://bankid.swedenconnect.se/idp
    base-url: https://local.dev.swedenconnect.se:${server.port}${server.servlet.context-path}    
    credentials:
      sign:
        resource: classpath:idp-credentials.jks
        alias: sign
        password: secret
        type: JKS
      encrypt:
        resource: classpath:idp-credentials.jks
        alias: encrypt
        password: secret
        type: JKS
      metadata-sign:
        resource: classpath:idp-credentials.jks
        alias: metadata
        password: secret
        type: JKS
    endpoints:
      metadata: /saml2/metadata    
    metadata-providers:
    - location: https://eid.svelegtest.se/metadata/mdx/role/sp.xml
      backup-location: target/metadata-backup.xml
      validation-certificate: classpath:sandbox-metadata.crt
    metadata:
      digest-methods:
      - http://www.w3.org/2001/04/xmlenc#sha256
      - http://www.w3.org/2001/04/xmldsig-more#sha384
      - http://www.w3.org/2001/04/xmlenc#sha512
      include-digest-methods-under-role: true
      signing-methods:
      - algorithm: http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
        min-key-size: 2048
      - algorithm: http://www.w3.org/2001/04/xmldsig-more#rsa-sha384
        min-key-size: 2048
      - algorithm: http://www.w3.org/2001/04/xmldsig-more#rsa-sha512
        min-key-size: 2048      
      - algorithm: http://www.w3.org/2007/05/xmldsig-more#sha256-rsa-MGF1
        min-key-size: 2048
      - algorithm: http://www.w3.org/2007/05/xmldsig-more#sha384-rsa-MGF1
        min-key-size: 2048
      - algorithm: http://www.w3.org/2007/05/xmldsig-more#sha512-rsa-MGF1
        min-key-size: 2048
      - algorithm: http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha256
        min-key-size: 256
      - algorithm: http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha384
        min-key-size: 256
      - algorithm: http://www.w3.org/2001/04/xmldsig-more#ecdsa-sha512
        min-key-size: 256
      include-signing-methods-under-role: true
      encryption-methods:
      - algorithm: http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p
      - algorithm: http://www.w3.org/2001/04/xmlenc#rsa-oaep-mgf1p
        digest-method: http://www.w3.org/2001/04/xmlenc#sha256
      - algorithm: http://www.w3.org/2009/xmlenc11#aes256-gcm
      - algorithm: http://www.w3.org/2009/xmlenc11#aes192-gcm
      - algorithm: http://www.w3.org/2009/xmlenc11#aes128-gcm
      - algorithm: http://www.w3.org/2001/04/xmlenc#aes256-cbc
      - algorithm: http://www.w3.org/2001/04/xmlenc#aes192-cbc
      - algorithm: http://www.w3.org/2001/04/xmlenc#aes128-cbc    
      requested-principal-selection:
      - "urn:oid:1.2.752.29.4.13"
      ui-info:
        display-names:
          en: BankID
          sv: BankID
        descriptions:
          en: BankID Identity Provider
          sv: BankID legitimeringstjänst
        logotypes:
        - path: /images/BankID_logo.svg
          height: 171
          width: 206   
      organization:
        names:
          en: Sweden Connect
          sv: Sweden Connect
        display-names:
          en: Sweden Connect
          sv: Sweden Connect
        urls:
          en: https://www.swedenconnect.se
          sv: https://www.swedenconnect.se
      contact-persons:
        technical:
          company: Sweden Connect
          email-addresses:
          - operations@swedenconnect.se
        support:
          company: Sweden Connect
          email-addresses:
          - operations@swedenconnect.se 
              
logging:
  level:
    se:
      swedenconnect:
        spring:
          saml: TRACE
---
spring:
  config:
    activate:
      on-profile: local
  redis:
    host: ${REDIS_HOST:local.dev.swedenconnect.se}
    port: ${REDIS_PORT:6379}
    password: supersecret
    ssl: true
    tls:
      p12KeyStorePath: classpath:local/redis/redis.p12
      p12KeyStorePassword: changeit
      p12TrustStorePath: classpath:local/redis/trust.p12
      p12TrustStorePassword: changeit
      enableHostnameVerification: true
  session:
    timeout: 15m
server:
  error:
    whitelabel:
      enabled: true
    path: /#error
  reactive:
    session:
      timeout: 15m

audit:
  event:
    module: default

session:
  module: redis

bankid:
  audit:
    module: "redistimeseries"
  builtinfrontend:
    disable: false
  server-root-certificate: classpath:bankid-trust-test.crt
  service-url: https://appapi2.test.bankid.com/rp/v6.0
  relying-parties:
  - id: test-my-eid
    entity-ids:
    - http://sandbox.swedenconnect.se/testmyeid
    - http://sandbox.swedenconnect.se/testmyeid-sign
    credential:
      name: "test-cred"
      resource: classpath:FPTestcert4_20220818.p12
      alias: "1"
      password: "qwerty123"
      type: "PKCS12"
    user-message:
      inherit-default-login-text: false
      login-text:
        text: "Jag loggar härmed in till tjänsten Testa ditt eID.\n\n*Tänk på!* Logga aldrig in med ditt BankID då någon ringer och ber dig logga in."
        format: simple-markdown-v1
    requirement:
      pin-code: false

saml:
  idp:
    entity-id: https://bankid.swedenconnect.se/idp/local
    base-url: https://local.dev.swedenconnect.se:${server.port}${server.servlet.context-path}
    metadata-providers:
    - location: classpath:local/local-metadata.xml

management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus, loggers, auditevents
  server:
    port: 8444
user:
  error:
    contact-email: contact@email.com
    show-contact-information: true
    show-trace-id: true
---
server:
  port: 8082

spring:
  config:
    activate:
      on-profile: sandbox
      
tomcat:
  ajp:
    enabled: true
    secret-required: true
    # secret is not set here ...
    port: 8012

bankid:
  server-root-certificate: classpath:bankid-trust-test.crt
  service-url: https://appapi2.test.bankid.com/rp/v6.0
  test-mode: true
  # Only one RP. This serves all SAML SP:s ... 
  relying-parties:
  - id: "test-rp"
    credential:
      name: "test-cred"
      resource: classpath:FPTestcert4_20220818.p12
      alias: "1"
      password: "qwerty123"
      type: "PKCS12"
    user-message:
      inherit-default-login-text: true

saml:
  idp:
    entity-id: https://sandbox.swedenconnect.se/bankid/idp
    base-url: https://sandbox.swedenconnect.se/bankid/idp

    
logging:
  level:
    se:
      swedenconnect:
        spring:
          saml: DEBUG
    

---
spring:
  config:
    activate:
      on-profile: integrationtest
bankid:
  audit:
    module: "redistimeseries"
  builtinfrontend:
    disable: false
  server-root-certificate: classpath:bankid-trust-test.crt
  service-url: https://appapi2.test.bankid.com/rp/v6.0
  relying-parties:
    - id: test-my-eid
      entity-ids:
        - https://demo.swedenconnect.se/sp
      credential:
        name: "test-cred"
        resource: classpath:FPTestcert4_20220818.p12
        alias: "1"
        password: "qwerty123"
        type: "PKCS12"
      user-message:
        inherit-default-login-text: false
        login-text:
          text: "Jag loggar härmed in till tjänsten Testa ditt eID.\n\n*Tänk på!* Logga aldrig in med ditt BankID då någon ringer och ber dig logga in."
          format: simple-markdown-v1
      requirement:
        pin-code: false