#
# Configuration for the BankID IdP.
#
server:
  port: 8443
  servlet:
    session:
      cookie:
        name: BANKIDSESSION
      timeout: 15m
    context-path: /bankid/idp
  ssl:
    enabled: true
    key-store: classpath:ssl.jks
    key-store-type: JKS
    key-alias: local
    key-store-password: secret
    key-password: secret
  error:
    include-message: always
    include-exception: true
    include-stacktrace: always
    path: "/icandothis"
spring:
  messages:
    basename: messages,idp-errors/idp-error-messages
    
bankid:
  server-root-certificate: classpath:bankid-trust-prod.crt
  service-url: https://appapi2.bankid.com/rp/v5.1
  qr-code:
    size: 300
    image-format: PNG
  user-message-defaults:
    fallback-sign-text:
      text: "Jag skriver härmed under den information som visades på föregående sida." 
      format: plain-text
    login-text:
      text: "*Tänk på!* Logga aldrig in med ditt BankID då någon ringer och ber dig logga in."
      format: simple-markdown-v1
  authn:
    resume-path: /resume 
    provider-name: "BankID"
    supported-loas:
    - http://id.swedenconnect.se/loa/1.0/uncertified-loa3
    entity-categories:
    - http://id.elegnamnden.se/ec/1.0/loa3-pnr
    - http://id.swedenconnect.se/ec/1.0/loa3-name
    - http://id.elegnamnden.se/sprop/1.0/mobile-auth
    - http://id.elegnamnden.se/sprop/1.0/scal2
    - http://id.swedenconnect.se/general-ec/1.0/secure-authenticator-binding    
    
ui:
  languages:
  - tag: sv
    text: Svenska
  - tag: en
    text: English    
    
#
# The SAML IdP configuration
#    
saml:
  idp:
    entity-id: https://bankid.swedenconnect.se/idp
    base-url: https://local.dev.swedenconnect.se:${server.port}/idp    
    credentials:
      sign:
        resource: classpath:idp-credentials.jks
        alias: sign
        password: secret
        type: JKS
      encrypt:
        resource: classpath:idp-credentials.jks
        alias: encrypt
        password: secret
        type: JKS
      metadata-sign:
        resource: classpath:idp-credentials.jks
        alias: metadata
        password: secret
        type: JKS
    endpoints:
      metadata: /saml2/metadata    
    metadata-providers:
    - location: https://eid.svelegtest.se/metadata/mdx/role/sp.xml
      backup-location: target/metadata-backup.xml
      validation-certificate: classpath:sandbox-metadata.crt
    metadata:
      ui-info:
        display-names:
          en: BankID
          sv: BankID
        descriptions:
          en: BankID Identity Provider
          sv: BankID legitimeringstjänst
        logotypes:
        - path: /images/BankID_logo.svg
          height: 171
          width: 206   
      organization:
        names:
          en: Sweden Connect
          sv: Sweden Connect
        display-names:
          en: Sweden Connect
          sv: Sweden Connect
        urls:
          en: https://www.swedenconnect.se
          sv: https://www.swedenconnect.se
      contact-persons:
        technical:
          company: Sweden Connect
          email-addresses:
          - operations@swedenconnect.se
        support:
          company: Sweden Connect
          email-addresses:
          - operations@swedenconnect.se 
              
logging:
  level:
    se:
      swedenconnect:
        spring:
          saml: TRACE

---

spring:
  redis:
    host: ${REDIS_HOST:local.dev.swedenconnect.se}
    port: ${REDIS_PORT:6379}
    password: supersecret
    ssl: true
    tls:
      p12KeyStorePath: classpath:local/redis/redis.p12
      p12KeyStorePassword: changeit
      p12TrustStorePath: classpath:local/redis/trust.p12
      p12TrustStorePassword: changeit
      enableHostnameVerification: true
  config:
    activate:
      on-profile: local
  session:
    timeout: 15m
server:
  reactive:
    session:
      timeout: 15m

audit:
  logging:
    module: default

session:
  module: redis

bankid:
  server-root-certificate: classpath:bankid-trust-test.crt
  service-url: https://appapi2.test.bankid.com/rp/v5.1
  relying-parties:
  - id: test-my-eid
    entity-ids:
    - http://sandbox.swedenconnect.se/testmyeid
    - http://sandbox.swedenconnect.se/testmyeid-sign
    credential:
      name: "test-cred"
      resource: classpath:FPTestcert4_20220818.p12
      alias: "1"
      password: "qwerty123"
      type: "PKCS12"
    user-message:
      inherit-default-login-text: false
      login-text:
        text: "Jag loggar härmed in till tjänsten Testa ditt eID.\n\n*Tänk på!* Logga aldrig in med ditt BankID då någon ringer och ber dig logga in."
        format: simple-markdown-v1
      

saml:
  idp:
    entity-id: https://bankid.swedenconnect.se/idp/local
    base-url: https://local.dev.swedenconnect.se:${server.port}/idp
    metadata-providers:
    - location: classpath:local/local-metadata.xml

---
server:
  port: 8082

spring:
  config:
    activate:
      on-profile: sandbox
      
tomcat:
  ajp:
    enabled: true
    secret-required: true
    # secret is not set here ...
    port: 8012

bankid:
  server-root-certificate: classpath:bankid-trust-test.crt
  service-url: https://appapi2.test.bankid.com/rp/v5.1
  test-mode: true
  # Only one RP. This serves all SAML SP:s ... 
  relying-parties:
  - id: "test-rp"
    credential:
      name: "test-cred"
      resource: classpath:FPTestcert4_20220818.p12
      alias: "1"
      password: "qwerty123"
      type: "PKCS12"
    user-message:
      inherit-default-login-text: true

saml:
  idp:
    entity-id: https://sandbox.swedenconnect.se/bankid/idp
    base-url: https://sandbox.swedenconnect.se/bankid/idp

    
logging:
  level:
    se:
      swedenconnect:
        spring:
          saml: DEBUG
    

