version: "3.9"

services:
  frontend:
    image: nginx:latest
    depends_on:
      - backend
    networks: 
      - idp
    ports:
      - 8000:80
      - 8443:443
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./selfsigned/sites/local.dev.swedenconnect.se.key:/etc/ssl/private/local.dev.swedenconnect.se.key
      - ./selfsigned/sites/local.dev.swedenconnect.se.crt:/etc/ssl/certs/local.dev.swedenconnect.se.crt
      - .self-signed.conf:/etc/nginx/snippets/self-signed.conf
      - .ssl-params.conf:/etc/nginx/snippets/ssl-params.conf
      - ./selfsigned/dhparam.pem:/etc/ssl/certs/dhparam.pem
  backend:
    image: local.dev.swedenconnect.se/bankid-saml-idp
    ports:
      - "8445:8445"
    volumes:
      - ./bankid-config:/opt/bankid-idp/
    environment:
      - SPRING_CONFIG_IMPORT=/opt/bankid-idp/externalized-frontend.yml
    depends_on:
      - redisstack
    networks:
      - idp
  redisstack:
     hostname: local.dev.swedenconnect.se
     image: redis/redis-stack:latest
     ports:
      - "6379:6379"
      - "8001:8001"
     networks:
      - idp
     volumes:
      - ../../bankid-idp/env/local/redis/certificates/:/tls
     environment:
      - REDIS_ARGS=--requirepass supersecret --tls-port 6379 --port 0 --tls-cert-file /tls/server.crt --tls-key-file /tls/server.key --tls-ca-cert-file /tls/ca.crt 

networks:
  idp:
    name: idp
